# Generated by Django 4.0.4 on 2022-07-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps_app', '0001_initial'),
        ('grenade_type_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grenade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_link', models.TextField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps_app.map')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grenade_type_app.grenadetype')),
            ],
            options={
                'verbose_name': 'Граната',
                'verbose_name_plural': 'Гранаты',
            },
        ),
    ]
