# Generated by Django 4.0.4 on 2022-07-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0001_initial'),
        ('publication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_post', to='tags_app.tag'),
        ),
    ]
