# Generated by Django 4.0.4 on 2022-07-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrenadeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Тип гранаты',
                'verbose_name_plural': 'Типы гранат',
            },
        ),
    ]
