# Generated by Django 4.0.4 on 2022-07-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0002_alter_map_pos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
